services:
  - type: web
    name: maquiavelicochat
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn proyecto.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: mi-django-db
