# Generated by Django 5.2.5 on 2025-08-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.IntegerField()),
            ],
        ),
    ]
