# Generated by Django 5.2.5 on 2025-08-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_usuarios_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
