# Generated by Django 5.2.5 on 2025-08-24 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_usuarios_contraseña'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('users', models.ManyToManyField(blank=True, related_name='salas_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
