# Generated by Django 5.2.5 on 2025-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='salas_joined', to='mi_app.usuarios'),
        ),
    ]
